const express = require("express")
const asyncMiddleware = require("../middleware/asyncMiddleware")
const authMiddleware = require("../middleware/auth.middleware")
const roleMiddleware = require("../middleware/role.middleware")
const typeUserRole = require("../constants/type.user.role")
const { getAllVPS, getVpsById, deleteVpsConfig, updateVPSById, createVPS } = require("../controller/vpsConfig.controller")
const vpsConfigRouter = express.Router()
vpsConfigRouter.route("/").get(asyncMiddleware(authMiddleware), roleMiddleware([typeUserRole.USER]), asyncMiddleware(getAllVPS))
vpsConfigRouter.route("/").get(asyncMiddleware(authMiddleware), roleMiddleware([typeUserRole.ADMIN]), asyncMiddleware(getAllVPS))
vpsConfigRouter.route("/:id").get(asyncMiddleware(authMiddleware), roleMiddleware([typeUserRole.USER]), asyncMiddleware(getVpsById))
vpsConfigRouter.route("/:id").delete(asyncMiddleware(authMiddleware), roleMiddleware([typeUserRole.ADMIN]), asyncMiddleware(deleteVpsConfig))
vpsConfigRouter.route("/:id").put(asyncMiddleware(authMiddleware), roleMiddleware([typeUserRole.ADMIN]), asyncMiddleware(updateVPSById))
vpsConfigRouter.route("/create").post(asyncMiddleware(authMiddleware), roleMiddleware([typeUserRole.USER]), asyncMiddleware(createVPS))
module.exports= vpsConfigRouter